// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBUmgRHK4btHqMf8Jq2ayuhkruA9-VAew',
    appId: '1:644146746823:web:255ac831685eb8b7d635e2',
    messagingSenderId: '644146746823',
    projectId: 'ecommshopping-b31ff',
    authDomain: 'ecommshopping-b31ff.firebaseapp.com',
    storageBucket: 'ecommshopping-b31ff.appspot.com',
    measurementId: 'G-DYMX7RP9J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4HeEgWxQR4anZJd_8LqQ1vjPTEcapxuo',
    appId: '1:644146746823:android:7f5d6c9e8e857191d635e2',
    messagingSenderId: '644146746823',
    projectId: 'ecommshopping-b31ff',
    storageBucket: 'ecommshopping-b31ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj9iR_JYOBiolt58lqwitIdko3MFr3Wjk',
    appId: '1:644146746823:ios:5279583aa362cb31d635e2',
    messagingSenderId: '644146746823',
    projectId: 'ecommshopping-b31ff',
    storageBucket: 'ecommshopping-b31ff.appspot.com',
    androidClientId: '644146746823-i8qdakvbrmgadj5odm0ebond2chdnv0h.apps.googleusercontent.com',
    iosClientId: '644146746823-4efo72ug9icmsvq7f5tv9uj220npg4ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj9iR_JYOBiolt58lqwitIdko3MFr3Wjk',
    appId: '1:644146746823:ios:bccc1d39aa5e288fd635e2',
    messagingSenderId: '644146746823',
    projectId: 'ecommshopping-b31ff',
    storageBucket: 'ecommshopping-b31ff.appspot.com',
    androidClientId: '644146746823-i8qdakvbrmgadj5odm0ebond2chdnv0h.apps.googleusercontent.com',
    iosClientId: '644146746823-jsrjcsef74sa2f5032q491jmhbit7ijo.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel.RunnerTests',
  );
}
